### ISSUE TITLE
Add Box option missing in drop down

### ISSUE THREAD

**Issue by VinitaJagannathan** [amiechen/Prettify#4]
The Add Box option is missing in the Add-ons list. All i get is the Help option.

![screenshot 49](https://cloud.githubusercontent.com/assets/19850926/16413644/b65aef66-3d50-11e6-8e7f-3982e4605c28.png)

**Comment by amiechen** [comment]
oh no! Try remove the add-ons and add it again, then you should see it. thanks for reporting the issue.

**Comment by VinitaJagannathan** [comment]
It is working fine today. Thank you :+1:
